alter table public.blog_posts
  add column if not exists offer_id text;

create table if not exists public.blog_post_offers (
  id bigint generated by default as identity primary key,
  post_id text not null,
  offer_id text not null,
  unique (post_id, offer_id)
);

alter table public.blog_post_offers
  add column if not exists sort_order integer not null default 0;

alter table public.blog_post_offers
  add column if not exists is_primary boolean not null default false;

alter table public.blog_post_offers
  add column if not exists created_at timestamptz not null default now();

alter table public.blog_post_offers
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_blog_post_offers_post_id
  on public.blog_post_offers (post_id);

create index if not exists idx_blog_post_offers_offer_id
  on public.blog_post_offers (offer_id);

create unique index if not exists idx_blog_post_offers_primary
  on public.blog_post_offers (post_id)
  where is_primary = true;
