import type {
  MicroCutBeat,
  MicroCutScene,
  MicroCutStoryboard,
  SocialCommerceCurrentSceneInput,
  SocialCommerceOfferInput,
} from "@/lib/commercial-video/social-commerce-v2/types";

function round(value: number): number {
  return Number(value.toFixed(2));
}

function priceText(price: number | null): string | null {
  return price === null ? null : `R$ ${price.toFixed(2).replace(".", ",")}`;
}

function beat(
  sceneId: string,
  index: number,
  startSecond: number,
  durationSeconds: number,
  data: Omit<MicroCutBeat, "beatId" | "beatIndex" | "startSecond" | "endSecond" | "durationSeconds">,
): MicroCutBeat {
  return {
    beatId: `${sceneId}-beat-${index}`,
    beatIndex: index,
    startSecond: round(startSecond),
    endSecond: round(startSecond + durationSeconds),
    durationSeconds: round(durationSeconds),
    ...data,
  };
}

function buildSceneBeats(scene: SocialCommerceCurrentSceneInput, startSecond: number, offer: SocialCommerceOfferInput): MicroCutBeat[] {
  const sceneId = scene.sceneId;
  const price = priceText(offer.price);
  if (scene.sceneNumber === 1 || scene.purpose === "HOOK") {
    return [
      beat(sceneId, 1, startSecond, 0.55, {
        purpose: "ATTENTION_SPIKE",
        beatGoal: "interromper o scroll no primeiro meio segundo com rosto vivo e produto ja insinuado",
        presenterMode: "REACTING_TO_FIND",
        productMode: "VISIBLE_EARLY",
        shotType: "FACE_CLOSE_REACTION",
        cameraDistance: "FACE_CLOSE",
        cameraMotion: "HANDHELD_MICRO_PUSH",
        bodyAction: "inclina levemente para frente como quem acabou de achar algo",
        facialExpression: "sobrancelha alta, sorriso curto de surpresa positiva",
        handAction: "levanta o produto parcialmente na borda do frame",
        eyeDirection: "camera direta",
        productInteraction: "produto aparece cedo sem bloquear o rosto",
        visualFocus: "expressao da Garota Radar + embalagem entrando",
        emotionalIntent: "descoberta real, curiosidade imediata",
        salesIntent: "abrir loop de achado barato antes de explicar",
        overlayIntent: "ACHADO DE SKINCARE",
        audioEnergyIntent: "hook com sorriso audivel, ritmo rapido, sem gritar",
        transitionIntent: "hard cut seco, sem abertura institucional",
        visualAction: "Garota Radar face close-up entra como creator mostrando um achado real.",
        narrationFragment: price ? `Gente, olha esse achado por so ${price}.` : "Gente, olha esse achado.",
        overlayFragment: "achado",
        transition: "HARD_CUT",
        sfxCue: "snap-in",
      }),
      beat(sceneId, 2, startSecond + 0.55, 0.55, {
        purpose: "HUMAN_REACTION",
        beatGoal: "mostrar que a apresentadora viu o preco/produto e reagiu",
        presenterMode: "REACTING_TO_FIND",
        productMode: "VISIBLE_EARLY",
        shotType: "LOOK_TO_SCREEN",
        cameraDistance: "MEDIUM_CLOSE",
        cameraMotion: "SNAP_ZOOM",
        bodyAction: "vira o ombro e volta para a camera",
        facialExpression: "cara de 'olha isso' sem exagero",
        handAction: "aponta curto para o produto/preco ao lado",
        eyeDirection: "produto/preco lateral e volta para camera",
        productInteraction: "produto permanece como objeto do achado",
        visualFocus: "olhar alternando entre espectador e produto",
        emotionalIntent: "surpresa positiva e cumplicidade",
        salesIntent: "fazer a audiencia sentir que chegou antes da oferta sumir",
        overlayIntent: "OLHA ISSO",
        audioEnergyIntent: "micro pausa curta depois de 'Gente'",
        transitionIntent: "snap zoom no olhar",
        visualAction: "Ela olha para o produto/preco como se tivesse acabado de confirmar o achado.",
        narrationFragment: null,
        overlayFragment: "olha isso",
        transition: "PUSH_IN",
        sfxCue: "short-rise",
      }),
      beat(sceneId, 3, startSecond + 1.1, 0.65, {
        purpose: "PRICE_POP",
        beatGoal: "transformar R$ 13,16 em gatilho de curiosidade, nao card frio",
        presenterMode: "REINFORCING_VALUE",
        productMode: "PRICE_ANCHOR",
        shotType: "POINTING_TO_OFFER",
        cameraDistance: "MEDIUM_CLOSE",
        cameraMotion: "STATIC_LOCK",
        bodyAction: "segura a pose para o overlay entrar limpo",
        facialExpression: "sorriso de surpresa controlada",
        handAction: "dedo aponta para a area segura do preco",
        eyeDirection: "preco depois camera",
        productInteraction: "produto e preco aparecem no mesmo eixo visual",
        visualFocus: "preco grande + rosto reagindo",
        emotionalIntent: "achado inacreditavel mas crivel",
        salesIntent: "dar motivo para continuar vendo",
        overlayIntent: price,
        audioEnergyIntent: "batida/sfx no pop do preco",
        transitionIntent: "price pop sincronizado com beat",
        visualAction: "Preco entra ao lado dela como pop de valor, sem mencionar marketplace.",
        narrationFragment: null,
        overlayFragment: price,
        transition: "POP",
        sfxCue: "price-pop",
      }),
      beat(sceneId, 4, startSecond + 1.75, Math.max(0.4, scene.durationSeconds - 1.75), {
        purpose: "HUMAN_REACTION",
        beatGoal: "fechar o hook prometendo teste/descoberta, nao explicacao longa",
        presenterMode: "REACTING_TO_FIND",
        productMode: "VISIBLE_EARLY",
        shotType: "SURPRISED_DISCOVERY",
        cameraDistance: "FACE_CLOSE",
        cameraMotion: "PUSH_IN",
        bodyAction: "aproxima o produto do rosto por um instante",
        facialExpression: "curiosa, animada, sorriso rapido",
        handAction: "mostra embalagem em gesto curto",
        eyeDirection: "camera direta",
        productInteraction: "produto vira prova visual do achado",
        visualFocus: "reacao humana com produto legivel",
        emotionalIntent: "quero testar isso",
        salesIntent: "levar para a demonstracao do produto",
        overlayIntent: "VALE TESTAR?",
        audioEnergyIntent: "voz compacta, final ascendente",
        transitionIntent: "match cut para detalhe de produto",
        visualAction: "Ela reage como creator que achou algo barato e quer testar agora.",
        narrationFragment: null,
        overlayFragment: "vale testar?",
        transition: "PUSH_IN",
        sfxCue: "match-swipe",
      }),
    ];
  }

  if (String(scene.purpose) === "PRODUCT" || String(scene.purpose) === "PRODUCT_DEMONSTRATION") {
    return [
      beat(sceneId, 1, startSecond, 0.7, {
        purpose: "PRODUCT_DETAIL",
        beatGoal: "ancorar o produto real e evitar vibe generica/suplemento",
        presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
        productMode: "PACKAGING_DETAIL",
        shotType: "PRODUCT_PACKAGING_LOCK",
        cameraDistance: "DETAIL_MACRO",
        cameraMotion: "STATIC_LOCK",
        bodyAction: "sem apresentadora; foco limpo no produto",
        facialExpression: "none",
        handAction: "mao entra para posicionar a embalagem",
        eyeDirection: "none",
        productInteraction: "embalagem real em bancada de skincare",
        visualFocus: "rotulo Kokeshi legivel",
        emotionalIntent: "produto concreto, nao mockup",
        salesIntent: "provar que o achado existe",
        overlayIntent: null,
        audioEnergyIntent: "fala curta, sem pausa longa",
        transitionIntent: "match cut do produto mostrado no hook",
        visualAction: "Embalagem real Kokeshi em pe, rotulo travado e legivel.",
        narrationFragment: "Esse e o Creme Gel Kokeshi.",
        overlayFragment: null,
        transition: "MATCH_CUT",
        sfxCue: "soft-tap",
      }),
      beat(sceneId, 2, startSecond + 0.7, 0.8, {
        purpose: "PRODUCT_EXPERIENCE",
        beatGoal: "tirar o produto do packshot e colocar em contexto de uso",
        presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
        productMode: "PACKAGING_DETAIL",
        shotType: "PRODUCT_MACRO",
        cameraDistance: "DETAIL_MACRO",
        cameraMotion: "HANDHELD_MICRO_PUSH",
        bodyAction: "sem apresentadora; mao humana guia a cena",
        facialExpression: "none",
        handAction: "segura o tubo de forma natural",
        eyeDirection: "none",
        productInteraction: "mao pega/segura o produto em bancada limpa de skincare",
        visualFocus: "produto em uso real, nao flutuando",
        emotionalIntent: "produto facil de experimentar",
        salesIntent: "reduzir distancia entre ver e testar",
        overlayIntent: null,
        audioEnergyIntent: "beat leve acompanhando o toque",
        transitionIntent: "hard cut para gesto de mao",
        visualAction: "Mao segura o tubo numa bancada limpa; produto fica aterrado no mundo real.",
        narrationFragment: null,
        overlayFragment: null,
        transition: "HARD_CUT",
        sfxCue: "product-touch",
      }),
      beat(sceneId, 3, startSecond + 1.5, 0.9, {
        purpose: "PRODUCT_EXPERIENCE",
        beatGoal: "criar desejo sensorial com textura/gel",
        presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
        productMode: "TEXTURE_OR_GEL",
        shotType: "PRODUCT_MACRO",
        cameraDistance: "DETAIL_MACRO",
        cameraMotion: "PUSH_IN",
        bodyAction: "sem apresentadora",
        facialExpression: "none",
        handAction: "aplica pequena gota/gel no dedo ou dorso da mao",
        eyeDirection: "none",
        productInteraction: "textura visivel com embalagem ao fundo ou em corte alternado",
        visualFocus: "consistencia gel/creme",
        emotionalIntent: "quero sentir/testar",
        salesIntent: "associar preco baixo a experiencia real",
        overlayIntent: "TEXTURA LEVE",
        audioEnergyIntent: "sfx pequeno de textura, musica continua",
        transitionIntent: "push-in macro",
        visualAction: "Corte macro de textura/aplicacao; creme visivel no dedo com embalagem referenciada.",
        narrationFragment: null,
        overlayFragment: "textura leve",
        transition: "PUSH_IN",
        sfxCue: "cream-dot",
      }),
      beat(sceneId, 4, startSecond + 2.4, Math.max(0.4, scene.durationSeconds - 2.4), {
        purpose: "PRODUCT_DETAIL",
        beatGoal: "voltar ao produto identificavel antes do argumento comercial",
        presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
        productMode: "APPLICATION_DEMO",
        shotType: "PRODUCT_PACKAGING_LOCK",
        cameraDistance: "DETAIL_MACRO",
        cameraMotion: "MATCH_MOVE",
        bodyAction: "sem apresentadora",
        facialExpression: "none",
        handAction: "fecha a embalagem ou recoloca ao lado da textura",
        eyeDirection: "none",
        productInteraction: "alternancia embalagem + textura na mesma composicao",
        visualFocus: "produto identificavel + experiencia de uso",
        emotionalIntent: "skincare simples e testavel",
        salesIntent: "preparar argumento de valor sem parecer demonstracao falsa",
        overlayIntent: "KOKESHI",
        audioEnergyIntent: "manter ritmo sem voz longa",
        transitionIntent: "match cut para Garota Radar",
        visualAction: "Retorno ao rotulo com textura/aplicacao ainda presente no contexto.",
        narrationFragment: null,
        overlayFragment: null,
        transition: "MATCH_CUT",
        sfxCue: null,
      }),
    ];
  }

  if (String(scene.purpose) === "OFFER") {
    return [
      beat(sceneId, 1, startSecond, 0.8, {
        purpose: "PRODUCT_DETAIL",
        beatGoal: "manter produto presente enquanto o preco entra como achado",
        presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
        productMode: "PRICE_ANCHOR",
        shotType: "PRODUCT_PACKAGING_LOCK",
        cameraDistance: "DETAIL_MACRO",
        cameraMotion: "STATIC_LOCK",
        bodyAction: "sem apresentadora",
        facialExpression: "none",
        handAction: "mao estabiliza produto fora da area do preco",
        eyeDirection: "none",
        productInteraction: "produto real em bancada com espaco para overlay",
        visualFocus: "produto + area limpa para preco",
        emotionalIntent: "clareza de valor",
        salesIntent: "preparar golpe de preco sem 0% off falso",
        overlayIntent: null,
        audioEnergyIntent: "preco falado com enfase curta",
        transitionIntent: "hard cut limpo para oferta",
        visualAction: "Produto real em close na bancada, com espaco seguro para overlay deterministico.",
        narrationFragment: price ? `So ${price}.` : "Olha a oferta real.",
        overlayFragment: null,
        transition: "HARD_CUT",
        sfxCue: "hit",
      }),
      beat(sceneId, 2, startSecond + 0.8, 0.8, {
        purpose: "OFFER_REVEAL",
        beatGoal: "fazer o preco parecer descoberta, nao card morto",
        presenterMode: "REINFORCING_VALUE",
        productMode: "PRICE_ANCHOR",
        shotType: "GRAPHIC_PRICE_CARD",
        cameraDistance: "GRAPHIC",
        cameraMotion: "SNAP_ZOOM",
        bodyAction: "sem apresentadora ou reacao rapida em picture-safe area",
        facialExpression: "surpresa positiva se houver insert humano",
        handAction: "seta/gesto grafico aponta para preco",
        eyeDirection: "preco",
        productInteraction: "produto permanece ao lado do preco",
        visualFocus: "R$ 13,16 grande + embalagem",
        emotionalIntent: "esse e o achado",
        salesIntent: "destacar valor sem alegar desconto",
        overlayIntent: price,
        audioEnergyIntent: "pop forte no preco",
        transitionIntent: "price pop no beat",
        visualAction: "Preco grande entra como overlay grafico; provider nunca renderiza texto de preco.",
        narrationFragment: null,
        overlayFragment: price,
        transition: "POP",
        sfxCue: "cash-pop",
      }),
      beat(sceneId, 3, startSecond + 1.6, Math.max(0.4, scene.durationSeconds - 1.6), {
        purpose: "RHYTHM_RESET",
        beatGoal: "fechar a oferta com produto e Radar Smart juntos",
        presenterMode: "REINFORCING_VALUE",
        productMode: "PRICE_ANCHOR",
        shotType: "POINTING_TO_OFFER",
        cameraDistance: "MEDIUM_CLOSE",
        cameraMotion: "PUSH_IN",
        bodyAction: "insert rapido da Garota Radar reagindo ao preco",
        facialExpression: "sorriso de achado",
        handAction: "aponta para o preco sem cobrir produto",
        eyeDirection: "preco e volta para camera",
        productInteraction: "produto ainda presente como prova",
        visualFocus: "preco, produto e reacao humana",
        emotionalIntent: "urgencia leve de oportunidade",
        salesIntent: "passar do valor para a acao",
        overlayIntent: "RADAR SMART",
        audioEnergyIntent: "short rise para CTA",
        transitionIntent: "whoosh curto para CTA",
        visualAction: "Acento rapido de produto/preco com reacao humana, ainda em contexto real.",
        narrationFragment: null,
        overlayFragment: "Radar Smart",
        transition: "PUSH_IN",
        sfxCue: "whoosh",
      }),
    ];
  }

  if (String(scene.purpose) === "CTA") {
    return [
      beat(sceneId, 1, startSecond, 0.9, {
        purpose: "CTA_PUSH",
        beatGoal: "reabrir contato humano com convite ativo",
        presenterMode: "INVITING_ACTION",
        productMode: "CTA_SUPPORT",
        shotType: "CTA_INVITATION",
        cameraDistance: "MEDIUM_CLOSE",
        cameraMotion: "HANDHELD_MICRO_PUSH",
        bodyAction: "aproxima meio corpo, postura inclinada para o espectador",
        facialExpression: "sorriso confiante, energia de convite",
        handAction: "gesto 'vem comigo'",
        eyeDirection: "camera direta",
        productInteraction: "produto pode aparecer pequeno como memoria visual",
        visualFocus: "Garota Radar convidando",
        emotionalIntent: "amizade e acao",
        salesIntent: "tirar do assistir para entrar no Radar Smart",
        overlayIntent: "GRUPO VIP",
        audioEnergyIntent: "CTA com sorriso e firmeza",
        transitionIntent: "hard cut para rosto ativo",
        visualAction: "Garota Radar em closer shot, gesto direto de convite.",
        narrationFragment: "Quer achar ofertas assim?",
        overlayFragment: "Grupo VIP",
        transition: "HARD_CUT",
        sfxCue: "soft-rise",
      }),
      beat(sceneId, 2, startSecond + 0.9, 1.0, {
        purpose: "CTA_PUSH",
        beatGoal: "deixar destino e proxima acao obvios",
        presenterMode: "INVITING_ACTION",
        productMode: "CTA_SUPPORT",
        shotType: "POINTING_TO_OFFER",
        cameraDistance: "MID",
        cameraMotion: "STATIC_LOCK",
        bodyAction: "abre espaco lateral para CTA",
        facialExpression: "confiante e animada",
        handAction: "aponta para area do botao/overlay",
        eyeDirection: "camera e overlay",
        productInteraction: "produto vira reforco secundario, nao protagonista",
        visualFocus: "Radar Smart + Grupo VIP",
        emotionalIntent: "convite real, nao encerramento frio",
        salesIntent: "clique/entrada no grupo",
        overlayIntent: "RADAR SMART",
        audioEnergyIntent: "frase curta, sem locucao institucional",
        transitionIntent: "CTA pop",
        visualAction: "Ela aponta para a area do CTA; Radar Smart e o destino claro.",
        narrationFragment: "Entra no Grupo VIP da Radar Smart.",
        overlayFragment: "Radar Smart",
        transition: "POP",
        sfxCue: "button-pop",
      }),
      beat(sceneId, 3, startSecond + 1.9, Math.max(0.4, scene.durationSeconds - 1.9), {
        purpose: "RHYTHM_RESET",
        beatGoal: "encerrar vivo e deixar promessa de novas ofertas",
        presenterMode: "INVITING_ACTION",
        productMode: "CTA_SUPPORT",
        shotType: "CTA_INVITATION",
        cameraDistance: "FACE_CLOSE",
        cameraMotion: "PUSH_IN",
        bodyAction: "micro aceno/final aberto",
        facialExpression: "sorriso final natural",
        handAction: "gesto curto para baixo/lateral do CTA",
        eyeDirection: "camera direta",
        productInteraction: "produto aparece como memoria visual ou overlay secundario",
        visualFocus: "rosto vivo + CTA",
        emotionalIntent: "continuidade, quero ver mais",
        salesIntent: "reforcar comunidade Radar Smart",
        overlayIntent: "OFERTAS COMO ESSA",
        audioEnergyIntent: "final ascendente, sem congelar",
        transitionIntent: "push-in final curto",
        visualAction: "Olhar final amigavel para camera, sem ending de apresentadora congelada.",
        narrationFragment: null,
        overlayFragment: "ofertas como essa",
        transition: "PUSH_IN",
        sfxCue: null,
      }),
    ];
  }

  return [
    beat(sceneId, 1, startSecond, 0.8, {
      purpose: "HUMAN_REACTION",
      beatGoal: "conectar preco baixo a vontade de testar",
      presenterMode: "REINFORCING_VALUE",
      productMode: "VISIBLE_EARLY",
      shotType: "HALF_BODY_CREATOR_DEMO",
      cameraDistance: "MEDIUM_CLOSE",
      cameraMotion: "HANDHELD_MICRO_PUSH",
      bodyAction: "meio corpo inclinado, energia de recomendacao curta",
      facialExpression: "sorriso pratico de quem aprovou o achado",
      handAction: "abre a palma em gesto de 'por esse preco'",
      eyeDirection: "camera direta",
      productInteraction: "produto aparece como insert ou na mao se disponivel",
      visualFocus: "Garota Radar ligando produto ao valor",
      emotionalIntent: "vale conhecer, sem anuncio duro",
      salesIntent: "transformar preco em baixa barreira de teste",
      overlayIntent: "VALE TESTAR",
      audioEnergyIntent: "tom de amiga, compacto",
      transitionIntent: "hard cut de reacao",
      visualAction: "Garota Radar reage ao produto/preco com energia creator.",
      narrationFragment: "Por esse preco, da vontade de testar.",
      overlayFragment: "vale testar",
      transition: "HARD_CUT",
      sfxCue: "reaction-pop",
    }),
    beat(sceneId, 2, startSecond + 0.8, 0.8, {
      purpose: "PRODUCT_DETAIL",
      beatGoal: "ancorar o argumento no produto real",
      presenterMode: "OFFSCREEN_PRODUCT_FOCUS",
      productMode: "PACKAGING_DETAIL",
      shotType: "PRODUCT_MACRO",
      cameraDistance: "DETAIL_MACRO",
      cameraMotion: "MATCH_MOVE",
      bodyAction: "sem apresentadora",
      facialExpression: "none",
      handAction: "mao reposiciona produto rapidamente",
      eyeDirection: "none",
      productInteraction: "detalhe de embalagem/textura retoma a experiencia",
      visualFocus: "produto real",
      emotionalIntent: "prova visual",
      salesIntent: "evitar frase solta sem produto",
      overlayIntent: null,
      audioEnergyIntent: "micro pausa visual, musica segura ritmo",
      transitionIntent: "match cut para produto",
      visualAction: "Cutaway rapido para detalhe de produto para ancorar a reacao no item.",
      narrationFragment: null,
      overlayFragment: null,
      transition: "MATCH_CUT",
      sfxCue: "soft-tap",
    }),
    beat(sceneId, 3, startSecond + 1.6, Math.max(0.4, scene.durationSeconds - 1.6), {
      purpose: "HUMAN_REACTION",
      beatGoal: "voltar para ela com recomendacao humana e nao institucional",
      presenterMode: "PRESENTING_PRODUCT",
      productMode: "VISIBLE_EARLY",
      shotType: "TRUSTED_RECOMMENDATION",
      cameraDistance: "MID",
      cameraMotion: "PUSH_IN",
      bodyAction: "meio corpo com maos visiveis",
      facialExpression: "confianca calorosa",
      handAction: "gesto pequeno de recomendacao",
      eyeDirection: "camera direta",
      productInteraction: "produto aparece em insert/overlay lateral",
      visualFocus: "recomendacao humana + produto",
      emotionalIntent: "amizade mostrando achado",
      salesIntent: "preparar o golpe de preco",
      overlayIntent: "ACHADO DE SKINCARE",
      audioEnergyIntent: "voz natural, sorriso, sem audiobook",
      transitionIntent: "push-in para oferta",
      visualAction: "Volta para apresentadora com tom pratico de recomendacao.",
      narrationFragment: null,
      overlayFragment: "achado de skincare",
      transition: "PUSH_IN",
      sfxCue: null,
    }),
  ];
}

export function buildMicroCutStoryboard(input: {
  scenes: SocialCommerceCurrentSceneInput[];
  offer: SocialCommerceOfferInput;
  totalDurationSeconds?: number;
}): MicroCutStoryboard {
  let cursor = 0;
  const microScenes: MicroCutScene[] = input.scenes.map((scene) => {
    const startSecond = cursor;
    const durationSeconds = scene.durationSeconds;
    const beats = buildSceneBeats(scene, startSecond, input.offer);
    cursor += durationSeconds;
    return {
      sceneId: scene.sceneId,
      macroPurpose: scene.purpose,
      startSecond: round(startSecond),
      endSecond: round(startSecond + durationSeconds),
      durationSeconds,
      beats,
      pacing: beats.length >= 3 ? "FAST_SOCIAL" : "CONTROLLED",
    };
  });

  const allBeats = microScenes.flatMap((scene) => scene.beats);
  const totalBeatDuration = allBeats.reduce((sum, item) => sum + item.durationSeconds, 0);

  return {
    version: "SOCIAL_COMMERCE_MICRO_CUT_STORYBOARD_V2",
    totalDurationSeconds: input.totalDurationSeconds ?? input.scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0),
    averageBeatDurationSeconds: round(totalBeatDuration / Math.max(1, allBeats.length)),
    scenes: microScenes,
  };
}
